

bot_token = "your_bot_token"

chat_id = "@your_chat_id"
folder_path = "./Tele"
max_retries = 3
timeout = 20
time_between_retries = 3
resize_max_dimension = 4096
resize_min_dimension = 320
allowed_extensions = [".jpg", ".jpeg", ".png", ".gif", ".bmp"]

[topics]

